[package]
name = "achilles"
version = "0.0.0"
authors = ["inkhare <iapricot@foxmail.com>"]
description = "A process level virtualization platform on Rust"
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["hypervisor", "virtualization"]