[package]
name = "socket"
version = "0.0.0"
authors = ["inkhare <iapricot@foxmail.com.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "socket"
crate-type = ["staticlib"]