[package]
name = "vmm"
version = "0.0.2"
authors = ["inkhare <iapricot@foxmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
kvm-bindings = { version = ">=0.5.0", features = ["fam-wrappers"] }
kvm-ioctls = "0.10.0"
libc = ">=0.2.39"
lazy_static = "1.4.0"